name: Link Checker

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  link-check:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress README.md
          fail: false

      - name: Create Issue on Failure
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Broken Links Found in README
          content-filepath: ./lychee/out.md
          labels: broken-links, maintenance
